"""Shared email HTML scaffolding for SalesPulse email builders.

Provides common wrappers, metric rows, and section headers so that
individual email builders (opportunity, customer, dashboard) stay DRY.
"""


# ── Shared styles ────────────────────────────────────────────────────────────

FONT_FAMILY = "Arial, sans-serif"
BG_COLOR = "#f9fafb"
CARD_SHADOW = "0 1px 4px rgba(0,0,0,.1)"
HEADER_BG = "#1e293b"
FOOTER_TEXT = "Generated by SalesPulse · AAA Western &amp; Central NY · Data from Salesforce"


def email_wrapper(title: str, body_html: str, header_bg: str = HEADER_BG,
                   subtitle: str = "SalesPulse", max_width: int = 700) -> str:
    """Wrap body_html in a complete HTML email document with consistent styling."""
    return (
        f'<!DOCTYPE html><html><body style="margin:0;padding:0;font-family:{FONT_FAMILY};background:{BG_COLOR}">'
        f'<div style="max-width:{max_width}px;margin:0 auto;background:#fff;border-radius:8px;'
        f'overflow:hidden;box-shadow:{CARD_SHADOW}">'
        f'  <div style="background:{header_bg};padding:20px 28px">'
        f'    <p style="margin:0 0 4px;font-size:12px;color:#94a3b8">{subtitle}</p>'
        f'    <h1 style="margin:0;font-size:20px;color:#fff;font-weight:700">{title}</h1>'
        f'  </div>'
        f'  <div style="padding:20px 28px">'
        f'    {body_html}'
        f'    <p style="font-size:10px;color:#9ca3af;margin-top:20px;border-top:1px solid #f3f4f6;padding-top:10px">'
        f'      {FOOTER_TEXT}'
        f'    </p>'
        f'  </div>'
        f'</div></body></html>'
    )


def metric_row(label: str, value: str, color: str | None = None) -> str:
    """Build a styled metric table row (label | value) for email KPI sections."""
    style = f'font-weight:600;color:{color}' if color else 'font-weight:500'
    return (
        f'<tr>'
        f'<td style="padding:4px 8px;font-size:12px;color:#6b7280;width:140px">{label}</td>'
        f'<td style="padding:4px 8px;font-size:12px;{style}">{value or "—"}</td>'
        f'</tr>'
    )


def section_header(text: str) -> str:
    """Build a styled section header for email bodies."""
    return (
        f'<h3 style="font-size:11px;font-weight:700;color:#374151;'
        f'text-transform:uppercase;letter-spacing:.05em;margin:0 0 8px">{text}</h3>'
    )
